[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.148.1'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

# Proxy Census Monkey Typewriter
[[redirects]]
  from = "/cmt/*"
  to = "https://dshkolcmt.netlify.app/:splat"
  status = 200

# Proxy The D-AI-LY
[[redirects]]
  from = "/thedaily/*"
  to = "https://dshkol-thedaily.netlify.app/:splat"
  status = 200
  force = true
